### ISSUE TITLE
Nested grids on mobile.

### ISSUE THREAD

**Issue by invantix** [nathansmith/adapt#10]
When you have nested grids and you are at mobile resolution, the nested divs are slightly indented.  I was able to fix this by adding the following to mobile.css and mobile.min.css:

.alpha { margin-left: 0; }
.omega { margin-left: 0; }

Notice that omega has left set to 0 instead of right because there is only one column.,

**Comment by nathansmith** [comment]
Thanks, I'll add this soon.

**Comment by invantix** [comment]
Actually I think this fixes issue #8.

**Comment by nathansmith** [comment]
That had to do with the fluid.css nesting being messed up.

But, the fix for that was easy. I just killed the fluid.css altogether (too buggy).
