### ISSUE TITLE
alternative to noscript

### ISSUE THREAD

**Issue by gagarine** [nathansmith/adapt#12]
The example use a noscript tag to load a mobile CSS.

``` html
  <noscript>
  <link rel="stylesheet" href="assets/css/mobile.min.css" />
  </noscript>
```

I don't think is a good idea because if a client than can do JS but behind a firewall than filter JS will end hup with no CSS at all.

I think it will be smarter to disable the mobile.css with JS but it will perhaps end up with a useless query.

I'm also curious witch CSS Google take (for the preview image on search result)

http://dev.opera.com/articles/view/replacing-noscript-with-accessible-un/

**Comment by nathansmith** [comment]
Yeah, the noscript approach is more or less just a suggestion, feel free to change it to accomodate the needs of your particular site. To answer your question about how search engines parse the page, this is what Google shows as the preview image...

http://cl.ly/3e1S040O2o3C0q040E2M
