### ISSUE TITLE
Feature request: Load multiple stylesheets for single range index

### ISSUE THREAD

**Issue by ghost** [nathansmith/adapt#14]
I admit it: I'm a stickler for organization. Sometimes it makes sense to split some rules into a separate file. In this particular instance, I've brought in a stylesheet from an outside source (you!) and, rather than risk overwriting my work when I apply an update on your file, I want to put all of my rules somewhere else.

e.g.:

```
<script>
  var ADAPT_CONFIG = {
    path: 'css/',
    dynamic: true,
    range: [
      '0  to 760 - mobile.min.css',
      '760 to 980 = 720.min.css',
      '760 to 980 = amended-styles.css',
      '980 = 980.min.css'
    ]
  };
</script>
```

Thanks!

**Comment by nathansmith** [comment]
I'd really like to keep Adapt simple, and just load one stylesheet per range.

But, what you could do, is in the amended-style.css file, do this...

```
@import '720.min.css'

/* Your styles to amend 720.min.css here */
```

It would be the same number of HTTP requests either way, and that would let you keep things organized.

As for your other open ticket/issue, I'll read through that carefully when I get a spare moment.

**Comment by othermachines** [comment]
Sensible! And I concur with wanting to keep things simple. Thanks!
