### ISSUE TITLE
Responsive site with adapt

### ISSUE THREAD

**Issue by gsuez** [nathansmith/adapt#19]
Hi Natham,
I integrated ADAPT to gantry framework 2 months ago, can you see: http://responsive.gsuez.cl/
works perfectly.
My question is: what about this issue?

"A potential drawback of Adapt.js is the possibility of a brief flash of unstyled content as a new stylesheet is being fetched (think of it as “Ajax” for CSS). I have done my best to mitigate this by keeping CSS files small (3 KB). It is worth noting this is a proposed, not prescribed, approach to a problem with multiple solutions. "

Any news?

Best regards

**Comment by nathansmith** [comment]
Unfortunately, that will always be a potential issue.

Really, if you don't need to support IE8 and lower, you could just use media queries.

Or, could just serve up a compiled stylesheet (via Sass or similar) of mobile, tablet, desktop… to IE8 and older.

So essentially IE8 and older would get the "desktop" version of the site, whereas good browsers (and IE9) would get the fully responsive experience.

That's the approach I'll be taking with future sites, if I can be assured (usually client's choice) that IE8 (and older) isn't a priority. And, when you think about it: IE8 and older can _only_ run on desktop, so it makes sense they'd get a desktop experience.

**Comment by nathansmith** [comment]
Update: This article explains the approach I was describing…

http://nicolasgallagher.com/mobile-first-css-sass-and-ie/

**Comment by gsuez** [comment]
Thank you for you feedback, Nathan!
as you say,IE8 is an old browser than all developers hated... But, you are right: for mobile, IE8 run only on desktop, fortunately! :)
The linked article is fantastic, perfectly explains this topic.
