### ISSUE TITLE
iphone landscape not taking proper css

### ISSUE THREAD

**Issue by umefarooq** [nathansmith/adapt#2]
Hi just testing your script on IOS simulator it is not taking proper css for landscape view of iphone, patriot view is fine.

**Comment by nathansmith** [comment]
Okay, I changed the index.html file's viewport scaling to: "width=device-width; minimum-scale=1; maximum-scale=1" which is what jQuery Mobile has. Can you please check again? Thanks. :)

**Comment by umefarooq** [comment]
no still the same problem no change at all

**Comment by nathansmith** [comment]
It looks correct to me. Note: There aren't supposed to be different files for phones (in portrait/landscape), just mobile.css.

Meaning, in either portrait or landscape, there shouldn't be any floated columns. It's all supposed to be linearized.

Here are two screenshots of what I see, which is what I have intended.

http://cl.ly/1x0n1c2g403H24371v1F

http://cl.ly/1s26261t0Z2P3A2G1e0e
