### ISSUE TITLE
bug when I run SSL

### ISSUE THREAD

**Issue by 3MotionX** [nathansmith/adapt#33]
Hi

I use SSL on my site, and i get this bug

`Mixed Content: The page at 'https://www.******.com/vb/' was loaded over HTTPS, but requested an insecure font 'http://themes.googleusercontent.com/static/fonts/archivonarrow/v3/DsLzC9scoPnrGiwYYMQXpp4t0mJKPaLVqklzZuc32b4.woff'. This request has been blocked; the content must be served over HTTPS. `

`Mixed Content: The page at 'https://www.********.com/vb/' was loaded over HTTPS, but requested an insecure font 'http://themes.googleusercontent.com/static/fonts/archivonarrow/v3/M__Wu4PAmHf4YZvQM8tWsHhM4mdXpoxYNWk7Ev34U70.woff'. This request has been blocked; the content must be served over HTTPS. `

`Mixed Content: The page at 'https://www.*******.com/vb/' was loaded over HTTPS, but requested an insecure font 'http://fonts.gstatic.com/s/montserrat/v6/zhcz-_WihjSQC0oHJ9TCYPk_vArhqVIZ0nv9q090hN8.woff2'. This request has been blocked; the content must be served over HTTPS.`

`Mixed Content: The page at 'https://www.*******.com/vb/' was loaded over HTTPS, but requested an insecure font 'http://fonts.gstatic.com/s/montserrat/v6/IQHow_FEYlDC4Gzy_m8fcoWiMMZ7xLd792ULpGE4W_Y.woff2'. This request has been blocked; the content must be served over HTTPS.`

how can I fix it ?

**Comment by nathansmith** [comment]
This has nothing to do with Adapt.js itself.

Rather, it's that your site is served over `https`, but you are pulling in assets that are served with `http`. You will need to point to the `https` version of Google Fonts.

**Instead of this:**

```
====
http://themes.googleusercontent.com/static/fonts/…
====
```

**Do this:**

```
=====
https://themes.googleusercontent.com/static/fonts/…
=====
```

**Comment by 3MotionX** [comment]
the problem is i couldn't find this url

> http://themes.googleusercontent.com/static/fonts/

you can check my site here
https://www.bb4arab.com/vb

please I need help

**Comment by nathansmith** [comment]
That was just an example, based on what you mentioned in your first comment.

I'm not saying that you must to have that specific URL in your HTML.

The main point is that everywhere you're linking to external, third party resources, just make sure to use `https` instead of `http`.
