### ISSUE TITLE
IE Browser issues

### ISSUE THREAD

**Issue by skully78** [nathansmith/adapt#4]
Hello, we have found a few issues with older IE browsers.
- IE7 - inconsistent layout when resizing - perhaps due to IE's sub-pixel rounding issue.
- IE6 - constant flickering after re-size event.

Thanks 
Skully

**Comment by nathansmith** [comment]
Skully:

Would you mind pasting what your config values look like?

**Comment by skully78** [comment]
Hi Nathan

I pointed the IE browsers to your site: http://adapt.960.gs/  and I am using native installs of IE6 and IE7 on windows XP SP3 machines. A quick replication of the bug can also be seen using IETester,  though we always test on native installs.

Its a pity some governmental websites still have to support IE6, But I am pushing for adaptive layouts :)

Thanks Skully.

**Comment by nathansmith** [comment]
Thanks, I've installed Windows XP on a VM to investigate. Hope to have a fix soon.

**Comment by nathansmith** [comment]
This has been fixed, and the latest version of adapt.js has been pushed.

**Comment by DAOTHITHUY1** [comment]
linhdao199yahoo.com@gmail.com
