### ISSUE TITLE
full width header?

### ISSUE THREAD

**Issue by weschyrchel** [nathansmith/adapt#7]
Any recommendations on how to create a full width header without a 10px margin on each end?

My apologies, but I have looked all over your text and on google and haven't found a solution, just hacks mostly.  Thought I would go to the source.  Any help would be appreciated.  Thanks!

**Comment by nathansmith** [comment]
If by "full width" you mean 960px wide, instead of 940px, just do...

```
#full_width_header {
  margin-left: auto;
  margin-right: auto;
  width: 960px;
}
```

Or, if the header is inside of a grid_12 (assuming a container_12 wrapper)...

```
#full_width_header {
  margin-left: -10px;
  margin-right: -10px;
}
```

**Comment by weschyrchel** [comment]
hmmm, the header is the grid_12, inside the container_12 wrapper.  Your
suggested margin, seems to just push it to the left.

#header {
background: url('images/hdr_bg.jpg') repeat-x top;
min-height: 48px;
margin: 0 -10px;
}

**Comment by nathansmith** [comment]
This should work...

http://host.sonspring.com/_misc/full_width_header.html

(Note, only included one grid CSS file, without adapt.js, in the interest of brevity)

**Comment by weschyrchel** [comment]
Okay, I see. I just need another container on the outside of the header.
 Thank you so much for the example!

Wes

**Comment by nathansmith** [comment]
Welcome! :)
